### ISSUE TITLE
Please keep updating the Calibre version! come on!

### ISSUE THREAD

**Issue by lottelucky** [Finios/calibre-server#2]
I have been following your version (updated according to the TAG version number), but the latest 5.42.0 update is broken, please continue, come on!

**Comment by Finios** [comment]
First, thank you for using my containerbuilds. I'm sorry for answering so late. 
I have automated my build a while ago and haven't checked my repo since then. I have tested the 5.42.0 build on two of my machines (with local build and pull from dockerhub). They were working fine on both. Can you describe what was/is broken in 5.42.0 on your side? Did the container not start? Did it crash with an error message?
